### ISSUE TITLE
id param docs out of date?

### ISSUE THREAD

**Issue by hcientist** [acbart/waltz#4]
[\_\_main__.py#L8](https://github.com/acbart/waltz/blob/master/waltz/__main__.py#L8) suggests that `id` is optional, but [sync.py#L138](https://github.com/acbart/waltz/blob/master/waltz/sync.py#L138) calling [sync.py#L34](https://github.com/acbart/waltz/blob/master/waltz/sync.py#L34) maybe disagrees?

```
TypeError: pull_all_resources() missing 1 required positional argument: 'ignore'
```

**Comment by acbart** [comment]
See #2 - I've just pushed my changes for V2 and merged the changes into master. The interface is different now.
