### ISSUE TITLE
waltz clone?

### ISSUE THREAD

**Issue by hcientist** [acbart/waltz#7]
Still how to start? Is it possible to begin by "cloning" my existing Canvas course? or am i basically requesting a new feature? 
e.g. `waltz pull canvas all`

**Comment by acbart** [comment]
I actually just finished that feature earlier today, if you pull. I believe the syntax should be:

```console
$ waltz pull canvas pages --all --destination pages/
$ waltz pull canvas assignments --all --destination assignments/
$ waltz pull canvas quizzes --all --destination quizzes/
```

If you don't do `--destination <path>`, then it gets placed in the current working directory. You need the `--all` parameter to get everything within that resource category. You do need to specify the service (`canvas`) and category (e.g., `pages`), though.

I was only trying it with `download` and `decode` directly, but `pull` should work the same way.

**Comment by hcientist** [comment]
Thanks!
are those all the categories?

**Comment by acbart** [comment]
For the Canvas service. Any other resources you need? I don't use most of the other types but it'd be easy to bring in some more. Eventually I figured I'd do the Module list, maybe Announcements, I guess Discussions. What do you use?

**Comment by hcientist** [comment]
Yeah, maybe modules, for some suuuuuuper regular classes it'd be helpful to have announcements (perhaps i'll find reusing announcements more since i've figured out the inbox and messaging feature and don't use announcements for all 1-off communiques 🤦‍♂️).

**Comment by acbart** [comment]
Opened #8 in response!
